swagger: "2.0"
info:
    title: Calculator Service
    description: Service for multiplying numbers, a Goa teaser
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /{id}:
        put:
            tags:
                - TestService
            summary: set TestService
            description: Set the workspace to be used
            operationId: TestService#set
            parameters:
                - name: id
                  in: path
                  description: Workspace ID
                  required: true
                  type: string
                - name: SetRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestServiceSetRequestBody'
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
        patch:
            tags:
                - TestService
            summary: update TestService
            description: Update an existing workspace information
            operationId: TestService#update
            parameters:
                - name: id
                  in: path
                  description: Workspace ID
                  required: true
                  type: string
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestServiceUpdateRequestBody'
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
definitions:
    TestServiceSetRequestBody:
        title: TestServiceSetRequestBody
        type: object
        properties:
            description:
                type: string
                example: Velit labore omnis.
            destination_ids:
                type: array
                items:
                    type: string
                    example: Voluptatum est enim possimus exercitationem beatae velit.
                example:
                    - Illum voluptatem possimus quidem excepturi et molestiae.
                    - Corporis dolore a in.
                    - Itaque quibusdam.
                    - Perferendis unde corrupti molestiae ipsa.
            logo_url:
                type: string
                example: Impedit dolor consectetur pariatur reiciendis.
            name:
                type: string
                example: Accusamus quia minus inventore accusamus voluptas illum.
        example:
            description: Quia dolorem fugit a nulla.
            destination_ids:
                - Ut beatae sint illo quam consequatur rerum.
                - Nostrum qui aut vero et.
                - Dolores eveniet blanditiis laudantium molestiae nobis dolorem.
            logo_url: Perferendis omnis dolores accusantium doloribus qui.
            name: Commodi iusto non accusantium illo aut.
    TestServiceUpdateRequestBody:
        title: TestServiceUpdateRequestBody
        type: object
        properties:
            description:
                type: string
                example: Qui mollitia.
            destination_ids:
                type: array
                items:
                    type: string
                    example: Quis consectetur voluptas.
                example:
                    - Consequatur maiores aut.
                    - Et consequatur quis dolorum corporis officiis rerum.
                    - Quia dolores consequatur cum itaque.
                    - Nam deserunt et tempora atque.
            logo_url:
                type: string
                example: Ea ut enim aut.
            name:
                type: string
                example: Unde omnis.
        example:
            description: Aut veritatis voluptas.
            destination_ids:
                - At fuga ut aliquam vel facilis facilis.
                - Qui recusandae rerum dolor aut officiis.
                - Voluptates rerum facere quas.
            logo_url: Quos est.
            name: Odit iusto vitae.
