openapi: 3.0.3
info:
    title: My Test API
    description: API for testing goa stuff
    version: "1.0"
servers:
    - url: http://localhost:80
paths:
    /:
        post:
            tags:
                - TestService
            summary: create TestService
            description: Create a new thing
            operationId: TestService#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            description: Similique rerum tempora quos totam quisquam voluptatibus.
                            id: Tempora aut.
                            name: Repudiandae perspiciatis est sint.
                            thing:
                                Description: Cumque laudantium aliquid ea.
            responses:
                "204":
                    description: No Content response.
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                description:
                    type: string
                    example: Dolorem velit explicabo.
                id:
                    type: string
                    example: Corporis qui commodi aut.
                name:
                    type: string
                    example: Enim et laudantium ad at vel amet.
                thing:
                    $ref: '#/components/schemas/SecondType'
            example:
                description: Commodi sed ut dolorem.
                id: Animi sapiente nobis commodi.
                name: Eius magnam tempore reiciendis unde.
                thing:
                    Description: Cumque laudantium aliquid ea.
        SecondType:
            type: object
            properties:
                Description:
                    type: string
                    example: Reprehenderit dolorem adipisci ut.
            example:
                Description: Vel beatae ea consequatur hic accusantium.
tags:
    - name: TestService
      description: The calc service performs operations on numbers.
