swagger: "2.0"
info:
    title: Calculator Service
    description: Service for multiplying numbers, a Goa teaser
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /{id}:
        put:
            tags:
                - TestService
            summary: set TestService
            description: Set the workspace to be used
            operationId: TestService#set
            parameters:
                - name: id
                  in: path
                  description: Workspace ID
                  required: true
                  type: string
                - name: SetRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestServiceSetRequestBody'
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
        patch:
            tags:
                - TestService
            summary: update TestService
            description: Update an existing workspace information
            operationId: TestService#update
            parameters:
                - name: id
                  in: path
                  description: Workspace ID
                  required: true
                  type: string
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestServiceUpdateRequestBody'
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
definitions:
    TestServiceSetRequestBody:
        title: TestServiceSetRequestBody
        type: object
        properties:
            description:
                type: string
                example: Rerum est nostrum qui aut vero.
            destination_ids:
                type: array
                items:
                    type: string
                    example: Labore dolores eveniet.
                example:
                    - Molestiae nobis dolorem sunt perferendis omnis.
                    - Accusantium doloribus.
                    - Ducimus dolore qui consequuntur qui dolor quis.
                    - Nostrum cumque deserunt labore hic.
            logo_url:
                type: string
                example: Qui dolores voluptas suscipit ut rerum.
            name:
                type: string
                example: Sed ut beatae sint illo quam.
        example:
            description: Nobis quo.
            destination_ids:
                - Ex sint dolor quo quidem voluptas excepturi.
                - Qui occaecati dolor.
                - Ratione aliquam quia neque odit temporibus.
                - Quae et sed fuga eos dolore et.
            logo_url: Qui autem consequatur sapiente aut unde aut.
            name: Sed ea nihil.
    TestServiceUpdateRequestBody:
        title: TestServiceUpdateRequestBody
        type: object
        properties:
            description:
                type: string
                example: Labore at fuga ut aliquam.
            destination_ids:
                type: array
                items:
                    type: string
                    example: Facilis facilis doloremque.
                example:
                    - Rerum dolor aut.
                    - Quos voluptates rerum facere quas deserunt.
                    - Est debitis accusamus quia minus inventore accusamus.
                    - Illum ea velit.
            logo_url:
                type: string
                example: Omnis debitis voluptatum est enim possimus exercitationem.
            name:
                type: string
                example: Aut veritatis voluptas.
        example:
            description: Excepturi et molestiae aperiam corporis dolore a.
            destination_ids:
                - Itaque quibusdam.
                - Perferendis unde corrupti molestiae ipsa.
                - Impedit dolor consectetur pariatur reiciendis.
                - Commodi iusto non accusantium illo aut.
            logo_url: Quia dolorem fugit a nulla.
            name: Velit consequuntur eum illum voluptatem possimus.
