swagger: "2.0"
info:
    title: My Test API
    description: API for testing goa stuff
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /:
        post:
            tags:
                - TestService
            summary: create TestService
            description: Create a new thing
            operationId: TestService#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestServiceCreateRequestBody'
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
definitions:
    SecondTypeRequestBody:
        title: SecondTypeRequestBody
        type: object
        properties:
            Description:
                type: string
                example: Omnis non non at.
        example:
            Description: Et explicabo aut exercitationem quasi necessitatibus.
    TestServiceCreateRequestBody:
        title: TestServiceCreateRequestBody
        type: object
        properties:
            description:
                type: string
                example: Aut aut rerum sed laudantium velit maxime.
            id:
                type: string
                example: Temporibus ratione sit voluptas est repudiandae.
            name:
                type: string
                example: Veritatis quam soluta dolores sunt.
            thing:
                $ref: '#/definitions/SecondTypeRequestBody'
        example:
            description: Harum beatae ab minus odit.
            id: Maxime iusto qui quo enim eveniet saepe.
            name: Quos dolorem illo ipsum nam dignissimos eveniet.
            thing:
                Description: Cumque laudantium aliquid ea.
